# Generated by Django 5.0.2 on 2024-02-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardTrip', '0002_alter_flight_origin_alter_flight_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
