# Generated by Django 5.0.2 on 2024-02-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardTrip', '0004_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='business_fare',
            new_name='fare',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='economy_fare',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='first_fare',
        ),
    ]
