# Generated by Django 5.0.2 on 2024-02-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardTrip', '0006_cities_delete_booked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
