# Generated by Django 5.0.2 on 2024-02-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardTrip', '0008_flight_destination_airport_flight_origin_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline_logo',
            field=models.ImageField(null=True, upload_to='uploaded'),
        ),
    ]
